version: 2.1
jobs:
  build:
    docker:
      - image: lisinge/asdf:latest
        environment:
          BASH_ENV: "~/.bashrc" # IMPORTANT!
    parameters:
      ruby-version:
        type: string
      active-record-version:
        type: string
    steps:
      - checkout
      - run:
          name: Intall build headers
          command: |
            apk add --no-cache linux-headers
            apk add --no-cache sqlite-dev

      - run:
          name: |
            Installing ruby << parameters.ruby-version >>
          command: |
            echo "---> Installing ASDF plugin for ruby"
            asdf plugin-add ruby

            echo "---> Installing ruby << parameters.ruby-version >>"
            asdf install ruby << parameters.ruby-version >>

            echo "---> Setting local ruby version"
            asdf local ruby << parameters.ruby-version >>

      - run:
          name: |
            Installing the correct version of the bundler gem
          command: |
            # install the bundler version that was used to build the lock file
            gem install bundler -v $(tail -1 Gemfile.lock | ruby -e "puts STDIN.read.strip")
            bundle config set --local path 'vendor/bundle'
            bundle install

      - run:
          name: |
            Installing rails << parameters.active-record-version >>
          command: |
            echo "---> Removing rails from bundle"
            bundle remove rails

            echo "---> Adding the correct version of rails to the bundle"
            bundle add --version=<< parameters.active-record-version >>

            bundle exec rake

      - run:
          name: Running build
          command: |
            bundle exec rake

workflows:
  all-tests:
    jobs:
      - build:
          matrix:
            parameters:
              ruby-version: [
                "2.0.0-p648", "2.1.10", "2.2.10", "2.3.8", "2.4.10", "2.5.9", "2.6.9",
                "2.7.5", "3.0.3", "3.1.0-preview1"
              ]
              active-record-version: ["~> 5.2.0", "~> 6.0.0", "~> 6.1.0", "~> 7.0.0"]
